;;;; raylib [textures] example - raw data
;;;;
;;;; Example complexity rating: [★★★☆] 3/4
;;;;
;;;; NOTE: Images are loaded in CPU memory (RAM); textures are loaded in GPU memory (VRAM)
;;;;
;;;; Example originally created with raylib 1.3, last time updated with raylib 3.5
;;;;
;;;; Example licensed under an unmodified zlib/libpng license, which is an OSI-certified,
;;;; BSD-like license that allows static linking with closed source software
;;;;
;;;; Copyright (c) 2015-2025 Ramon Santamaria (@raysan5)
;;;; Common Lisp port of raylib/examples/textures/textures_raw_data.c

(require :cl-raylib)

(defpackage #:raylib-examples/textures-raw-data
  (:use #:cl #:raylib))
(in-package #:raylib-examples/textures-raw-data)

;;------------------------------------------------------------------------------------
;; Program main entry point
;;------------------------------------------------------------------------------------
(defun main ()
  ;; Initialization
  ;;--------------------------------------------------------------------------------------
  (let ((screen-width 800)
        (screen-height 450))

    (init-window screen-width screen-height "raylib [textures] example - raw data")

    ;; NOTE: Textures MUST be loaded after Window initialization (OpenGL context is required)

    ;; Load RAW image data (512x512, 32bit RGBA, no file header)
    (let* ((fudesumi-raw (load-image-raw "resources/fudesumi.raw" 384 512 +pixelformat-uncompressed-r8g8b8a8+ 0))
           (fudesumi (load-texture-from-image fudesumi-raw)) ; Upload CPU (RAM) image to GPU (VRAM)

           ;; Generate a checked texture by code
           (im-width 960)
           (im-height 480)

           ;; Pixels data (Color type, R8G8B8A8)
           (pixels (make-array (* im-width im-height 4) :element-type '(unsigned-byte 8))))
      (unload-image fudesumi-raw)       ; Unload CPU (RAM) image data

      (dotimes (y im-height)
        (dotimes (x im-width)
          (replace pixels (if (= (mod (+ (truncate x 32) (truncate y 32)) 2) 0) +orange+ +gold+)
                   :start1 (* (+ (* y im-width) x) 4))))

      ;; Load pixels data into an image structure and create texture
      ;; NOTE: We can assign pixels directly to data because Color is R8G8B8A8
      ;; data structure defining that pixelformat, format must be set properly
      (let* ((checked-im (make-image :data pixels
                                     :width im-width
                                     :height im-height
                                     :format +pixelformat-uncompressed-r8g8b8a8+
                                     :mipmaps 1))
             (checked (load-texture-from-image checked-im)))
        (unload-image checked-im)       ; Unload CPU (RAM) image data (pixels)

        (set-target-fps 60)             ; Set our game to run at 60 frames-per-second
        ;;---------------------------------------------------------------------------------------

        ;; Main game loop
        (loop until (window-should-close) ; Detect window close button or ESC key
              do ;; Update
                 ;;----------------------------------------------------------------------------------
                 ;; TODO: Update your variables here
                 ;;----------------------------------------------------------------------------------

                 ;; Draw
                 ;;----------------------------------------------------------------------------------
                 (begin-drawing)

                 (clear-background +raywhite+)

                 (draw-texture checked (- (truncate screen-width 2) (truncate (texture-width checked) 2))
                               (- (truncate screen-height 2) (truncate (texture-height checked) 2)) (fade +white+ 0.5))
                 (draw-texture fudesumi 430 -30 +white+)

                 (draw-text "CHECKED TEXTURE " 84 85 30 +brown+)
                 (draw-text "GENERATED by CODE" 72 148 30 +brown+)
                 (draw-text "and RAW IMAGE LOADING" 46 210 30 +brown+)

                 (draw-text "(c) Fudesumi sprite by Eiden Marsal" 310 (- screen-height 20) 10 +brown+)

                 (end-drawing))
        ;;----------------------------------------------------------------------------------

        ;; De-Initialization
        ;;--------------------------------------------------------------------------------------
        (unload-texture fudesumi)       ; Texture unloading
        (unload-texture checked)        ; Texture unloading

        (close-window)))))              ; Close window and OpenGL context

(main)
