;;;; raylib [others] example - embedded files loading
;;;;
;;;; Example complexity rating: [★★☆☆] 2/4
;;;;
;;;; Example originally created with raylib 3.0, last time updated with raylib 3.5
;;;;
;;;; Example contributed by Kristian Holmgren (@defutura) and reviewed by Ramon Santamaria (@raysan5)
;;;;
;;;; Example licensed under an unmodified zlib/libpng license, which is an OSI-certified,
;;;; BSD-like license that allows static linking with closed source software
;;;;
;;;; Copyright (c) 2020-2025 Kristian Holmgren (@defutura) and Ramon Santamaria (@raysan5)
;;;; Common Lisp port of raylib/examples/others/embedded_files_loading.c

(require :cl-raylib)

(defpackage #:raylib-examples/embedded-files-loading
  (:use #:cl #:raylib))
(in-package #:raylib-examples/embedded-files-loading)

;; NOTE: The C example #includes headers generated by ExportWaveAsCode()/ExportImageAsCode();
;; here INCLUDE-CODE-HEADER parses those same headers at macroexpansion time, so their #define values
;; become constants and the byte array is embedded in the compiled code as a literal
(eval-when (:compile-toplevel :load-toplevel :execute)
  (defun read-code-header (file)
    "Parse a raylib *AsCode header: returns the byte array and an alist of its #define values"
    (let ((text (uiop:read-file-string file))
          (whitespace '(#\Space #\Tab #\Newline #\Return)))
      (values
       (let* ((start (1+ (position #\{ text)))
              (end (position #\} text :start start))
              ;; NOTE: Scan the 0x.. tokens directly: uiop:split-string is quadratic on ECL for MB-sized text
              (bytes (loop with i = start
                           for p = (search "0x" text :start2 i :end2 end)
                           while p
                           collect (let ((j (or (position-if-not (lambda (c) (digit-char-p c 16)) text
                                                                 :start (+ p 2) :end end)
                                                end)))
                                     (prog1 (parse-integer text :start (+ p 2) :end j :radix 16)
                                       (setf i j))))))
         (make-array (length bytes) :element-type '(unsigned-byte 8) :initial-contents bytes))
       (with-input-from-string (s text)
         (loop for line = (read-line s nil)
               while line
               when (uiop:string-prefix-p "#define" line)
                 collect (destructuring-bind (define name value &rest comment)
                             (remove "" (uiop:split-string line :separator whitespace) :test #'string=)
                           (declare (ignore define comment))
                           (cons name (parse-integer value)))))))))

(defmacro include-code-header (file data-name)
  (multiple-value-bind (bytes defines)
      (read-code-header (merge-pathnames file (or *compile-file-truename* *load-truename*)))
    `(progn
       ,@(loop for (name . value) in defines
               collect `(defconstant ,(intern (format nil "+~a+" (substitute #\- #\_ name))) ,value))
       (defparameter ,data-name ,bytes))))

(include-code-header "resources/audio_data.h" *audio-data*) ; Wave file exported with ExportWaveAsCode()
(include-code-header "resources/image_data.h" *image-data*) ; Image file exported with ExportImageAsCode()

;; 32bit wave data is exported as the bytes of a float array, decode them to the Wave sample array
(defun bytes-to-floats (bytes)
  (let ((samples (make-array (floor (length bytes) 4) :element-type 'single-float)))
    (dotimes (i (length samples) samples)
      (setf (aref samples i)
            (ieee-floats:decode-float32 (logior (aref bytes (* i 4))
                                                (ash (aref bytes (+ (* i 4) 1)) 8)
                                                (ash (aref bytes (+ (* i 4) 2)) 16)
                                                (ash (aref bytes (+ (* i 4) 3)) 24)))))))

;;------------------------------------------------------------------------------------
;; Program main entry point
;;------------------------------------------------------------------------------------
(defun main ()
  ;; Initialization
  ;;--------------------------------------------------------------------------------------
  (let ((screen-width 800)
        (screen-height 450))

    (init-window screen-width screen-height "raylib [others] example - embedded files loading")

    (init-audio-device)                 ; Initialize audio device

    ;; Loaded in CPU memory (RAM) from header file (audio_data.h)
    ;; Same as: (load-wave "sound.wav")
    (let* ((wave (make-wave :data (bytes-to-floats *audio-data*)
                            :frame-count +audio-frame-count+
                            :sample-rate +audio-sample-rate+
                            :sample-size +audio-sample-size+
                            :channels +audio-channels+))

           ;; Wave converted to Sound to be played
           (sound (load-sound-from-wave wave))

           ;; With a Wave loaded from file, after Sound is loaded, we can unload Wave
           ;; but in our case, Wave is embedded in the program code, we do not unload it
           ;;(unload-wave wave)          ; Do not unload wave data!

           ;; Loaded in CPU memory (RAM) from header file (image_data.h)
           ;; Same as: (load-image "raylib_logo.png")
           (image (make-image :data *image-data*
                              :width +image-width+
                              :height +image-height+
                              :format +image-format+
                              :mipmaps 1))

           ;; Image converted to Texture (VRAM) to be drawn
           (texture (load-texture-from-image image)))

      ;; With an Image loaded from file, after Texture is loaded, we can unload Image
      ;; but in our case, Image is embedded in the program code, we do not unload it
      ;;(unload-image image)           ; Do not unload image data!

      (set-target-fps 60)               ; Set our game to run at 60 frames-per-second
      ;;--------------------------------------------------------------------------------------

      ;; Main game loop
      (loop until (window-should-close) ; Detect window close button or ESC key
            do ;; Update
               ;;----------------------------------------------------------------------------------
               (when (is-key-pressed +key-space+) (play-sound sound)) ; Play sound
               ;;----------------------------------------------------------------------------------

               ;; Draw
               ;;----------------------------------------------------------------------------------
               (begin-drawing)

               (clear-background +raywhite+)

               (draw-texture texture (- (floor screen-width 2) (floor (texture-width texture) 2)) 40 +white+)

               (draw-text "raylib logo and sound loaded from header files" 150 320 20 +lightgray+)
               (draw-text "Press SPACE to PLAY the sound!" 220 370 20 +lightgray+)

               (end-drawing))
      ;;----------------------------------------------------------------------------------

      ;; De-Initialization
      ;;--------------------------------------------------------------------------------------
      (unload-sound sound)              ; Unload sound from VRAM
      (unload-texture texture)          ; Unload texture from VRAM

      (close-audio-device)              ; Close audio device

      (close-window))))                 ; Close window and OpenGL context

(main)
