(defpackage #:cl-raylib-util
  (:use #:cl #:cffi)
  (:export #:translate-name-from-foreign
           #:translate-name-to-foreign
           #:define-conversion-into-foreign-memory
           #:define-conversion-from-foreign))

(defpackage #:cl-raylib
  (:nicknames #:raylib)
  (:use #:cl #:cffi #:alexandria #:cl-raylib-util)
  (:export
   #:make-rgba

   #:make-vector2
   #:vector2-x
   #:vector2-y

   #:make-vector3
   #:vector3-x
   #:vector3-y
   #:vector3-z

   #:make-vector4
   #:vector4-x
   #:vector4-y
   #:vector4-z
   #:vector4-w

   #:make-rectangle
   #:rectangle-x
   #:rectangle-y
   #:rectangle-width
   #:rectangle-height

   #:make-texture
   #:texture-id
   #:texture-width
   #:texture-height
   #:texture-mipmaps
   #:texture-format

   #:make-render-texture
   #:render-texture-id
   #:render-texture-texture
   #:render-texture-depth
   #:render-texture-depth-texture

   #:make-patch-info
   #:patch-info-rec
   #:patch-info-left
   #:patch-info-top
   #:patch-info-right
   #:patch-info-bottom
   #:patch-info-type

   #:make-char-info
   #:char-info-value
   #:char-info-offset-x
   #:char-info-offset-y
   #:char-info-advance-x
   #:char-info-image

   #:make-font
   #:font-base-size
   #:font-chars-count
   #:font-texture
   #:font-recs
   #:font-chars

   #:make-camera3d
   #:camera3d-position
   #:camera3d-target
   #:camera3d-up
   #:camera3d-fovy
   #:camera3d-type

   #:make-camera2d
   #:camera2d-offset
   #:camera2d-target
   #:camera2d-rotation
   #:camera2d-zoom

   #:init-window
   #:window-should-close
   #:close-window
   #:is-window-ready
   #:is-window-minimized
   #:is-window-resized
   #:is-window-hidden
   #:is-window-fullscreen
   #:toggle-fullscreen
   #:unhide-window
   #:hide-window
   #:set-window-icon
   #:set-window-title
   #:set-window-position
   #:set-window-monitor
   #:set-window-min-size
   #:set-window-size
   #:get-window-handle
   #:get-screen-width
   #:get-screen-height
   #:get-monitor-count
   #:get-monitor-width
   #:get-monitor-height
   #:get-monitor-physical-width
   #:get-monitor-physical-height
   #:get-window-position
   #:get-monitor-name
   #:get-clipboard-text
   #:set-clipboard-text
   #:show-cursor
   #:hide-cursor
   #:is-cursor-hidden
   #:enable-cursor
   #:disable-cursor
   #:clear-background
   #:begin-drawing
   #:end-drawing
   #:begin-mode-2d
   #:end-mode-2d
   #:begin-mode-3d
   #:end-mode-3d
   #:begin-texture-mode
   #:end-texture-mode
   #:begin-scissor-mode
   #:end-scissor-mode
   #:get-mouse-ray
   #:get-camera-matrix
   #:get-camera-matrix-2d
   #:get-world-to-screen
   #:set-target-fps
   #:get-fps
   #:get-frame-time
   #:get-time
   #:color-to-int
   #:color-normalize
   #:color-from-normalized
   #:color-to-hsv
   #:color-from-hsv
   #:get-color
   #:fade
   #:set-config-flags
   #:set-trace-log-level
   #:set-trace-log-exit
   #:trace-log
   #:take-screenshot
   #:get-random-value
   #:load-file-data
   #:save-file-data
   #:load-file-text
   #:save-file-text
   #:file-exists
   #:is-file-extension
   #:directory-exists
   #:get-extension
   #:get-file-name
   #:get-file-name-without-ext
   #:get-directory-path
   #:get-prev-directory-path
   #:get-working-directory
   #:get-directory-files
   #:change-directory
   #:is-file-dropped
   #:get-dropped-files
   #:clear-dropped-files
   #:get-file-mod-time
   #:compress-data
   #:decompress-data
   #:save-storage-value
   #:load-storage-value
   #:open-url
   #:is-key-pressed
   #:is-key-down
   #:is-key-released
   #:is-key-up
   #:set-exit-key
   #:get-key-pressed
   #:is-gamepad-available
   #:is-gamepad-name
   #:get-gamepad-name
   #:is-gamepad-button-pressed
   #:is-gamepad-button-down
   #:is-gamepad-button-released
   #:is-gamepad-button-up
   #:get-gamepad-button-pressed
   #:get-gamepad-axis-count
   #:get-gamepad-axis-movement
   #:is-mouse-button-pressed
   #:is-mouse-button-down
   #:is-mouse-button-released
   #:is-mouse-button-up
   #:get-mouse-x
   #:get-mouse-y
   #:get-mouse-position
   #:set-mouse-position
   #:set-mouse-offset
   #:set-mouse-scale
   #:get-mouse-wheel-move
   #:get-touch-x
   #:get-touch-y
   #:get-touch-position
   #:set-gestures-enabled
   #:is-gesture-detected
   #:get-gesture-detected
   #:get-touch-points-count
   #:get-gesture-hold-duration
   #:get-gesture-drag-vector
   #:get-gesture-drag-angle
   #:get-gesture-pinch-vector
   #:get-gesture-pinch-angle
   #:set-camera-mode
   #:update-camera
   #:set-camera-pan-control
   #:set-camera-alt-control
   #:set-camera-smooth-zoom-control
   #:set-camera-move-controls
   #:draw-pixel
   #:draw-pixel-v
   #:draw-line
   #:draw-line-v
   #:draw-line-ex
   #:draw-line-bezier
   #:draw-line-bezier-quad
   #:draw-line-bezier-cubic
   #:draw-line-strip
   #:draw-circle
   #:draw-circle-sector
   #:draw-circle-sector-lines
   #:draw-circle-gradient
   #:draw-circle-v
   #:draw-circle-lines
   #:draw-ellipse
   #:draw-ellipse-lines
   #:draw-ring
   #:draw-ring-lines
   #:draw-rectangle
   #:draw-rectangle-v
   #:draw-rectangle-rec
   #:draw-rectangle-pro
   #:draw-rectangle-gradient-v
   #:draw-rectangle-gradient-h
   #:draw-rectangle-gradient-ex
   #:draw-rectangle-lines
   #:draw-rectangle-lines-ex
   #:draw-rectangle-rounded
   #:draw-rectangle-rounded-lines
   #:draw-triangle
   #:draw-triangle-lines
   #:draw-triangle-fan
   #:draw-triangle-strip
   #:draw-poly
   #:draw-poly-lines
   #:check-collision-recs
   #:check-collision-circles
   #:check-collision-circle-rec
   #:get-collision-rec
   #:check-collision-point-rec
   #:check-collision-point-circle
   #:check-collision-point-triangle
   #:load-image
   #:load-image-ex
   #:load-image-pro
   #:load-image-raw
   #:unload-image
   #:export-image
   #:export-image-as-code
   #:get-image-data
   #:get-image-data-normalized
   #:gen-image-color
   #:gen-image-gradient-v
   #:gen-image-gradient-h
   #:gen-image-gradient-radial
   #:gen-image-checked
   #:gen-image-white-noise
   #:gen-image-perlin-noise
   #:gen-image-cellular
   #:image-copy
   #:image-from-image
   #:image-text
   #:image-text-ex
   #:image-to-pot
   #:image-format
   #:image-alpha-mask
   #:image-alpha-clear
   #:image-alpha-crop
   #:image-alpha-premultiply
   #:image-crop
   #:image-resize
   #:image-resize-n-n
   #:image-resize-canvas
   #:image-mipmaps
   #:image-dither
   #:image-flip-vertical
   #:image-flip-horizontal
   #:image-rotate-cw
   #:image-rotate-ccw
   #:image-color-tint
   #:image-color-invert
   #:image-color-grayscale
   #:image-color-contrast
   #:image-color-brightness
   #:image-color-replace
   #:image-extract-palette
   #:get-image-alpha-border
   #:load-texture
   #:load-texture-from-image
   #:load-texture-cubemap
   #:load-render-texture
   #:unload-texture
   #:unload-render-texture
   #:update-texture
   #:get-texture-data
   #:get-screen-data
   #:gen-texture-mipmaps
   #:set-texture-filter
   #:set-texture-wrap
   #:draw-texture
   #:draw-texture-v
   #:draw-texture-ex
   #:draw-texture-rec
   #:draw-texture-quad
   #:draw-texture-pro
   #:draw-texture-n-patch
   #:get-font-default
   #:load-font
   #:load-font-ex
   #:load-font-from-image
   #:load-font-data
   #:unload-font
   #:draw-fps
   #:draw-text
   #:draw-text-ex
   #:draw-text-rec
   #:draw-text-rec-ex
   #:draw-text-codepoint
   #:measure-text
   #:measure-text-ex
   #:get-glyph-index
   #:text-copy
   #:text-is-equal
   #:text-length
   #:text-format
   #:text-subtext
   #:text-replace
   #:text-insert
   #:text-join
   #:text-split
   #:text-append
   #:text-find-index
   #:text-to-upper
   #:text-to-lower
   #:text-to-pascal
   #:text-to-integer
   #:text-to-utf8
   #:get-codepoints
   #:get-codepoints-count
   #:get-next-codepoint
   #:codepoint-to-utf8
   #:draw-line-3d
   #:draw-circle-3d
   #:draw-cube
   #:draw-cube-v
   #:draw-cube-wires
   #:draw-cube-wires-v
   #:draw-cube-texture
   #:draw-sphere
   #:draw-sphere-ex
   #:draw-sphere-wires
   #:draw-cylinder
   #:draw-cylinder-wires
   #:draw-plane
   #:draw-ray
   #:draw-grid
   #:draw-gizmo
   #:load-model
   #:load-model-from-mesh
   #:unload-model
   #:load-meshes
   #:export-mesh
   #:unload-mesh
   #:load-materials
   #:load-material-default
   #:unload-material
   #:set-material-texture
   #:set-model-mesh-material
   #:load-model-animations
   #:update-model-animation
   #:unload-model-animation
   #:is-model-animation-valid
   #:gen-mesh-plane
   #:gen-mesh-cube
   #:gen-mesh-sphere
   #:gen-mesh-hemi-sphere
   #:gen-mesh-cylinder
   #:gen-mesh-torus
   #:gen-mesh-knot
   #:gen-mesh-heightmap
   #:gen-mesh-cubicmap
   #:mesh-bounding-box
   #:mesh-tangents
   #:mesh-binormals
   #:draw-model
   #:draw-model-ex
   #:draw-model-wires
   #:draw-model-wires-ex
   #:draw-bounding-box
   #:draw-billboard
   #:draw-billboard-rec
   #:calculate-bounding-box
   #:check-collision-spheres
   #:check-collision-boxes
   #:check-collision-box-sphere
   #:check-collision-ray-sphere
   #:check-collision-ray-sphere-ex
   #:check-collision-ray-box
   #:get-collision-ray-model
   #:get-collision-ray-triangle
   #:get-collision-ray-ground
   #:load-shader
   #:load-shader-from-memory
   #:unload-shader
   #:get-shader-default
   #:get-texture-default
   #:get-shapes-texture
   #:get-shapes-texture-rec
   #:set-shapes-texture
   #:get-shader-location
   #:set-shader-value
   #:set-shader-value-v
   #:set-shader-value-matrix
   #:set-shader-value-texture
   #:set-matrix-projection
   #:set-matrix-modelview
   #:get-matrix-modelview
   #:get-matrix-projection
   #:gen-texture-cubemap
   #:gen-texture-irradiance
   #:gen-texture-prefilter
   #:gen-texture-brdf
   #:begin-shader-mode
   #:end-shader-mode
   #:begin-blend-mode
   #:end-blend-mode
   #:init-vr-simulator
   #:close-vr-simulator
   #:update-vr-tracking
   #:set-vr-configuration
   #:is-vr-simulator-ready
   #:toggle-vr-mode
   #:begin-vr-drawing
   #:end-vr-drawing
   #:init-audio-device
   #:close-audio-device
   #:is-audio-device-ready
   #:set-master-volume
   #:load-wave
   #:load-sound
   #:load-sound-from-wave
   #:update-sound
   #:unload-wave
   #:unload-sound
   #:export-wave
   #:export-wave-as-code
   #:play-sound
   #:pause-sound
   #:resume-sound
   #:play-sound-multi
   #:stop-sound-multi
   #:get-sounds-playing
   #:is-sound-playing
   #:set-sound-volume
   #:set-sound-pitch
   #:wave-format
   #:wave-copy
   #:wave-crop
   #:get-wave-data
   #:load-music-stream
   #:unload-music-stream
   #:play-music-stream
   #:update-music-stream
   #:stop-music-stream
   #:pause-music-stream
   #:resume-music-stream
   #:is-music-playing
   #:set-music-volume
   #:set-music-pitch
   #:get-music-loop-count
   #:get-music-time-length
   #:get-music-time-played
   #:init-audio-stream
   #:update-audio-stream
   #:close-audio-stream
   #:is-audio-stream-processed
   #:play-audio-stream
   #:pause-audio-stream
   #:resume-audio-stream
   #:is-audio-stream-palying
   #:stop-audio-stream
   #:set-audio-stream-volume
   #:set-audio-stream-pitch
   #:set-audio-stream-buffer-size-default


   ;; high level api
   #:with-window
   #:with-drawing
   #:with-mode-2d
   #:with-mode-3d
   #:with-texture-mode
   #:with-shader-mode
   #:with-blend-mode
   #:with-vr-simulator
   #:with-vr-drawing
   #:with-audio-device
   #:with-audio-stream
   #:with-sound))

(defpackage #:cl-rlgl
  (:nicknames #:rlgl)
  (:use #:cl #:cffi #:alexandria #:cl-raylib-util)
  (:export
   #:+texture-wrap-s+
   #:+texture-wrap-t+
   #:+texture-map-filter+
   #:+texture-min-filter+
   
   #:+texture-filter-nearest+
   #:+texture-filter-linear+
   #:+texture-filter-mip-nearest+
   #:+texture-filter-nearest-mip-linear+
   #:+texture-filter-linear-mip-nearest+
   #:+texture-filter-mip-linear+
   #:+texture-filter-anisotropic+
   #:+texture-mipmap-bias-ratio+

   #:+texture-wrap-repeat+
   #:+texture-wrap-clamp+
   #:+texture-wrap-mirror-repeat+
   #:+texture-wrap-minnor-clamp+

   #:+modelview+
   #:+projection+
   #:+texture+

   #:+lines+
   #:+triangles+
   #:+quads+

   #:+unsigned-byte+
   #:+float+

   #:+stream-draw+
   #:+stream-read+
   #:+stream-copy+
   #:+static-draw+
   #:+static-read+
   #:+static-copy+
   #:+dynamic-draw+
   #:+dynamic-read+
   #:+dynamic-copy+

   #:+fragment-shader+
   #:+vertext-shader+
   #:+compute-shader+

   #:+zero+
   #:+one+
   #:+src-color+
   #:+one-minu-src-color+
   #:+src-alpha+
   #:+one-minus-src-alpha+
   #:+dst-alpha+
   #:+one-minus-dst-alpha+
   #:+dst-color+
   #:+one-minus-dst-color+
   #:+src-alpha-saturate+
   #:+constant-color+
   #:+one-minus-constant-color+
   #:+constant-alpha+
   #:+one-minus-constant-alpha+

   #:+func-add+
   #:+min+
   #:+max+
   #:+func-subtract+
   #:+func-reverse-subtract+
   #:+blend-equation+
   #:+blend-equation-rgb+
   #:+blend-equation-alpha+
   #:+blend-dst-rgb+
   #:+blend-src-rgb+
   #:+blend-dst-alpha+
   #:+blend-src-alpha+
   #:+blend-color+

   #:%VertexBuffer
   #:%DrawCall
   #:%RenderBatch

   #:matrix-mode
   #:push-matrix
   #:pop-matrix
   #:load-identity
   #:translate-f
   #:rotate-f
   #:scale-f
   #:mult-matrix-f
   #:frustum
   #:ortho
   #:viewport
   #:begin
   #:end
   #:vertex-2i
   #:vertex-2f
   #:vertex-3f
   #:textcoord-2f
   #:normal-3f
   #:color-4ub
   #:color-3f
   #:color-4f
   #:enable-vertext-array
   #:disable-vertext-array
   #:enable-vertex-buffer
   #:disable-vertex-buffer
   #:enable-vertex-buffer-element
   #:disable-vertex-buffer-element
   #:enable-vertex-buffer-attribute
   #:disable-vertex-buffer-attribute
   #:active-texture-slot
   #:enable-texture
   #:disable-texture
   #:enable-texture-cubemap
   #:disable-texture-cubemap
   #:texture-parameters
   #:cubemap-parameters
   #:enable-shader
   #:disable-shader
   #:enable-framebuffer
   #:disable-framebuffer
   #:active-draw-buffers
   #:enable-color-blend
   #:disable-color-blend
   #:enable-depth-test
   #:disable-depth-test
   #:enable-depth-mask
   #:disable-depth-mask
   #:enable-backface-culling
   #:disable-backface-culling
   #:set-cull-face
   #:enable-scissor-test
   #:disable-scissor-test
   #:scissor
   #:enable-wire-mode
   #:disable-wire-mode
   #:set-line-width
   #:get-line-width
   #:enable-smooth-lines
   #:disable-smooth-lines
   #:enable-stereo-render
   #:disable-sterea-render
   #:is-stereo-render-enabled
   #:clear-color
   #:clear-screen-buffers
   #:check-errors
   #:set-blend-mode
   #:set-blend-factors
   #:set-blend-factors-separate
   
   #:rlgl-init
   #:rlgl-close
   #:load-extensions
   #:get-version
   
   #:set-framebuffer-width
   #:get-framebuffer-width
   #:set-framebuffer-height
   #:get-framebuffer-height
   
   #:get-texture-id-default
   #:get-shader-id-default
   #:get-shader-locs-default
   
   #:load-render-batch
   #:unload-render-batch
   #:draw-render-batch
   #:set-render-batch-active
   #:draw-render-batch-active
   #:check-render-batch-limit
   
   #:set-texture
   
   #:load-vertex-array
   #:load-vertex-buffer
   #:load-vertext-buffer-element
   #:update-vertex-buffer
   #:update-vertex-buffer-elements
   #:unload-vertex-array
   #:unload-vertex-buffer
   #:set-vertex-attribute
   #:set-vertex-attribute-divisor
   #:set-vertex-attribute-default
   #:draw-vertex-array
   #:draw-vertex-array-elements
   #:draw-vertex-array-instanced
   #:draw-vertex-array-elements-instanced
   
   #:load-texture
   #:load-texture-depth
   #:load-texture-cubemap
   #:update-texture
   #:get-gl-texture-formats
   #:get-pixel-format-name
   #:unload-texture
   #:gen-texture-mipmaps
   #:read-texture-pixels
   #:read-screen-pixels
   
   #:load-framebuffer
   #:framebuffer-attach
   #:framebuffer-complete
   #:unload-framebuffer
   
   #:load-shader-code
   #:compile-shader
   #:load-shader-program
   #:unload-shader-program
   #:get-location-uniform
   #:get-location-attrib
   #:set-uniform
   #:set-uniform-matrix
   #:set-uniform-sampler
   #:set-shader
   #:load-compute-shader-program
   #:compute-shader-dispatch
   #:load-shader-buffer
   #:unload-shader-buffer
   #:update-shader-buffer
   #:bind-shader-buffer
   #:read-shader-buffer
   #:copy-shader-buffers
   #:get-shader-buffer-size
   #:bind-image-texture
   
   #:get-matrix-modelview
   #:get-matrix-projection
   #:get-matrix-transform
   #:get-matrix-projection-stereo
   #:get-matrix-view-offset-stereo
   #:set-matrix-projection
   #:set-matrix-modelview
   #:set-matrix-projection-stereo
   #:set-matrix-view-offset-stereo
   #:load-draw-cube
   #:load-draw-quad))
