(defpackage #:cl-raylib
  (:nicknames #:raylib)
  (:use #:cl #:cffi #:alexandria)
  (:export #:init-window
           #:close-window
           #:window-should-close
           #:is-window-minimized
           #:toggle-fullscreen
           #:get-screen-width
           #:get-screen-height
           #:show-cursor
           #:hide-cursor
           #:is-cursor-hidden
           #:enable-cursor
           #:disable-cursor
           #:clear-background
           #:begin-drawing
           #:end-drawing
           #:begin-2d-mode
           #:end-2d-mode
           #:begin-3d-mode
           #:end-3d-mode
           #:begin-texture-mode
           #:end-texture-mode
           #:get-mouse-ray
           #:get-world-to-screen
           #:get-camera-matrix
           #:set-target-fps
           #:get-fps
           #:get-frame-time
           #:get-color
           #:get-hex-value
           #:color-to-float
           #:vector-to-float
           #:matrix-to-float
           #:get-random-value
           #:fade
           #:set-config-flags
           #:show-logo
           #:is-file-dropped
           #:get-file-dropped
           #:clear-dropped-files
           #:storage-save-value
           #:storage-load-value
           #:is-key-pressed
           #:is-key-down
           #:is-key-released
           #:is-key-up
           #:get-key-pressed
           #:set-exit-key
           #:is-gamepad-available
           #:is-gamepad-name
           #:get-gamepad-name
           #:is-gamepad-button-pressed
           #:is-gamepad-button-down
           #:is-gamepad-button-released
           #:is-gamepad-button-up
           #:get-gamepad-button-pressed
           #:get-gamepad-axis-count
           #:get-gamepad-axis-movement
           #:is-mouse-button-pressed
           #:is-mouse-button-down
           #:is-mouse-button-released
           #:is-mouse-button-up
           #:get-mouse-x
           #:get-mouse-y
           #:get-mouse-position
           #:set-mouse-position
           #:get-mouse-wheel-move
           #:get-touch-x
           #:get-touch-y
           #:get-touch-position
           #:set-gestures-enabled
           #:is-gesture-detected
           #:get-gesture-detected
           #:get-touch-points-count
           #:get-gesture-hold-duration
           #:get-gesture-drag-vector
           #:get-gesture-drag-angle
           #:get-gesture-pinch-vector
           #:get-gesture-pinch-angle
           #:set-camera-mode
           #:update-camera
           #:set-camera-pan-control
           #:set-camera-alt-control
           #:set-camera-smooth-zoom-control
           #:set-camera-move-controls
           #:draw-pixel
           #:draw-pixel-v
           #:draw-line
           #:draw-line-v
           #:draw-circle
           #:draw-circle-gradient
           #:draw-circle-v
           #:draw-circle-lines
           #:draw-rectangle
           #:draw-rectangle-rec
           #:draw-rectangle-gradient
           #:draw-rectangle-v
           #:draw-rectangle-lines
           #:draw-triangle
           #:draw-triangle-lines
           #:draw-poly
           #:draw-poly-ex
           #:draw-poly-ex-lines
           #:check-collision-recs
           #:check-collision-circles
           #:check-collision-circle-rec
           #:get-collision-rec
           #:check-collision-point-rec
           #:check-collision-point-circle
           #:check-collision-point-triangle
           #:load-image
           #:load-image-ex
           #:load-image-raw
           #:load-image-from-res
           #:load-texture
           #:load-texture-ex
           #:load-texture-from-res
           #:load-texture-from-image
           #:load-render-texture
           #:unload-image
           #:unload-texture
           #:unload-render-texture
           #:get-image-data
           #:get-texture-data
           #:update-texture
           #:image-to-p-o-t
           #:image-format
           #:image-alpha-mask
           #:image-dither
           #:image-copy
           #:image-crop
           #:image-resize
           #:image-resize-n-n
           #:image-text
           #:image-text-ex
           #:image-draw
           #:image-draw-text
           #:image-draw-text-ex
           #:image-flip-vertical
           #:image-flip-horizontal
           #:image-color-tint
           #:image-color-invert
           #:image-color-grayscale
           #:image-color-contrast
           #:image-color-brightness
           #:gen-texture-mipmaps
           #:set-texture-filter
           #:set-texture-wrap
           #:draw-texture
           #:draw-texture-v
           #:draw-texture-ex
           #:draw-texture-rec
           #:draw-texture-pro
           #:get-default-font
           #:load-sprite-font
           #:load-sprite-font-t-t-f
           #:unload-sprite-font
           #:draw-text
           #:draw-text-ex
           #:measure-text
           #:measure-text-ex
           #:draw-fps
           #:format-text
           #:sub-text
           #:draw-line-3-d
           #:draw-circle-3-d
           #:draw-cube
           #:draw-cube-v
           #:draw-cube-wires
           #:draw-cube-texture
           #:draw-sphere
           #:draw-sphere-ex
           #:draw-sphere-wires
           #:draw-cylinder
           #:draw-cylinder-wires
           #:draw-plance
           #:draw-ray
           #:draw-grid
           #:draw-gizmo
           #:draw-light
           #:load-model
           #:load-model-ex
           #:load-model-from-res
           #:load-heightmap
           #:load-cubicmap
           #:unload-model
           #:load-material
           #:load-default-materialard-material
           #:load-standard-material
           #:unload-material
           #:draw-model
           #:draw-model-ex
           #:draw-model-wires
           #:draw-model-wires-ex
           #:draw-bounding-box
           #:draw-billboard
           #:draw-billboard-rec
           #:calculate-bounding-box
           #:check-collision-spheres
           #:check-collision-boxes
           #:check-collision-box-sphere
           #:check-collision-ray-sphere
           #:check-collision-ray-sphere-ex
           #:check-collision-ray-box
           #:load-shader
           #:unload-shader
           #:get-default-shader
           #:get-standard-shader
           #:get-default-texture
           #:get-shader-location
           #:set-shader-value
           #:set-shader-valuei
           #:set-shader-value-matrix
           #:set-matrix-projection
           #:set-matrix-modelview
           #:begin-shader-mode
           #:end-shader-mode
           #:begin-blend-mode
           #:end-blend-mode
           #:create-light
           #:destroy-light
           #:init-vr-device
           #:close-vr-device
           #:is-vr-device-ready
           #:is-vr-simulator
           #:update-vr-tracking
           #:toggle-vr-mode
           #:init-audio-device
           #:close-audio-device
           #:is-audio-device-ready
           #:load-wave
           #:load-wave-ex
           #:load-sound
           #:load-sound-from-wave
           #:load-sound-from-res
           #:update-sound
           #:unload-wave
           #:unload-sound
           #:play-sound
           #:pause-sound
           #:resume-sound
           #:stop-sound
           #:is-sound-playing
           #:set-sound-volume
           #:set-sound-pitch
           #:wave-format
           #:wave-copy
           #:wave-crop
           #:get-wave-data
           #:load-music-stream
           #:unload-music-stream
           #:play-music-stream
           #:update-music-stream
           #:stop-music-stream
           #:pause-music-stream
           #:resume-music-stream
           #:is-music-playing
           #:set-music-volume
           #:set-music-pitch
           #:get-music-time-length
           #:get-music-time-played
           #:init-audio-stream
           #:update-audio-stream
           #:close-audio-stream
           #:is-audio-buffer-processed
           #:play-audio-stream
           #:pause-audio-stream
           #:resume-audio-stream
           #:stop-audio-stream

           #:+lightgray+
           #:+gray+
           #:+darkgray+
           #:+yellow+
           #:+gold+
           #:+orange+
           #:+pink+
           #:+red+
           #:+maroon+
           #:+green+
           #:+lime+
           #:+darkgreen+
           #:+skyblue+
           #:+blue+
           #:+darkblue+
           #:+purple+
           #:+violet+
           #:+darkpurple+
           #:+beige+
           #:+brown+
           #:+darkbrown+
           #:+white+
           #:+black+
           #:+blank+
           #:+magenta+
           #:+raywhite+

           ;; high level api
           #:with-window
           #:with-drawing))
