(in-package #:cl-raylib)

;;;===================================================================================
;;; sdefl - Small DEFLATE (RFC 1951) compressor
;;; Port of raylib/src/external/sdefl.h (used by rcore.c CompressData())
;;;===================================================================================

(defconstant +sdefl-max-off+ (ash 1 15))
(defconstant +sdefl-win-siz+ +sdefl-max-off+)
(defconstant +sdefl-win-msk+ (1- +sdefl-win-siz+))

(defconstant +sdefl-hash-bits+ 15)
(defconstant +sdefl-hash-siz+ (ash 1 +sdefl-hash-bits+))

(defconstant +sdefl-min-match+ 4)
(defconstant +sdefl-blk-max+ (* 256 1024))

(defconstant +sdefl-sym-max+ 288)
(defconstant +sdefl-off-max+ 32)
(defconstant +sdefl-pre-max+ 19)

(defconstant +sdefl-nil+ -1)
(defconstant +sdefl-max-match+ 258)
(defconstant +sdefl-sym-bits+ 10)
(defconstant +sdefl-sym-msk+ (1- (ash 1 +sdefl-sym-bits+)))
(defconstant +sdefl-raw-blk-size+ 65535)
(defconstant +sdefl-lit-len-codes+ 14)
(defconstant +sdefl-off-codes+ 15)
(defconstant +sdefl-pre-codes+ 7)
(defconstant +sdefl-eob+ 256)

(deftype %u32-vector () '(simple-array (unsigned-byte 32) (*)))

(defstruct (sdefl (:constructor %make-sdefl))
  (bits 0 :type fixnum) (bitcnt 0 :type fixnum)
  (tbl (make-array +sdefl-hash-siz+ :element-type 'fixnum :initial-element 0) :type (simple-array fixnum (*)))
  (prv (make-array +sdefl-win-siz+ :element-type 'fixnum :initial-element 0) :type (simple-array fixnum (*)))
  (seq (make-array 0 :adjustable t :fill-pointer 0))   ; (off . len)
  ;; struct sdefl_freq
  (freq-lit (make-array +sdefl-sym-max+ :element-type '(unsigned-byte 32) :initial-element 0) :type %u32-vector)
  (freq-off (make-array +sdefl-off-max+ :element-type '(unsigned-byte 32) :initial-element 0) :type %u32-vector)
  ;; struct sdefl_codes
  (word-lit (make-array +sdefl-sym-max+ :element-type '(unsigned-byte 32) :initial-element 0) :type %u32-vector)
  (word-off (make-array +sdefl-off-max+ :element-type '(unsigned-byte 32) :initial-element 0) :type %u32-vector)
  (len-lit (make-array +sdefl-sym-max+ :element-type '(unsigned-byte 8) :initial-element 0))
  (len-off (make-array +sdefl-off-max+ :element-type '(unsigned-byte 8) :initial-element 0))
  ;; output
  (out nil))

(declaim (inline %sdefl-ilog2 %sdefl-npow2 %sdefl-div-round-up))
(defun %sdefl-ilog2 (n) (if (zerop n) 0 (1- (integer-length n))))
(defun %sdefl-npow2 (n) (ash 1 (+ (%sdefl-ilog2 (1- n)) 1)))
(defun %sdefl-div-round-up (n d) (floor (+ n (1- d)) d))

(declaim (inline %sdefl-uload32 %sdefl-hash32))
(defun %sdefl-uload32 (in p)
  (declare (type (simple-array (unsigned-byte 8) (*)) in) (type fixnum p))
  (flet ((b (k) (let ((i (+ p k))) (if (< i (length in)) (aref in i) 0))))
    (logior (b 0) (ash (b 1) 8) (ash (b 2) 16) (ash (b 3) 24))))
(defun %sdefl-hash32 (in p)
  (ash (logand (* (%sdefl-uload32 in p) #x9E377989) #xffffffff) (- (- 32 +sdefl-hash-bits+))))

(defun %sdefl-put (s code bitcnt)
  (setf (sdefl-bits s) (logior (sdefl-bits s) (ash code (sdefl-bitcnt s))))
  (incf (sdefl-bitcnt s) bitcnt)
  (loop while (>= (sdefl-bitcnt s) 8)
        do (vector-push-extend (logand (sdefl-bits s) #xff) (sdefl-out s))
           (setf (sdefl-bits s) (ash (sdefl-bits s) -8))
           (decf (sdefl-bitcnt s) 8)))

;;; Heap sort over A[base+1 .. base+len] (1-based like sdefl after A--)
(defun %sdefl-heap-sub (a base len sub)
  (let* ((p sub) (v (aref a (+ base sub))) (c 0))
    (loop while (<= (setf c (ash p 1)) len)
          do (when (and (< c len) (> (aref a (+ base c 1)) (aref a (+ base c)))) (incf c))
             (when (>= v (aref a (+ base c))) (return))
             (setf (aref a (+ base p)) (aref a (+ base c)) p c))
    (setf (aref a (+ base p)) v)))

(defun %sdefl-heap-sort (a start n)
  (let ((base (1- start)))
    (loop for sub downfrom (ash n -1) to 1 do (%sdefl-heap-sub a base n sub))
    (loop while (>= n 2)
          do (rotatef (aref a (+ base n)) (aref a (+ base 1)))
             (decf n)
             (%sdefl-heap-sub a base n 1))))

(defun %sdefl-sort-sym (sym-cnt freqs lens sym-out)
  (let* ((cnt-num (logand (+ sym-cnt 3) (lognot 3)))     ; SDEFL_CNT_NUM()
         (cnts (make-array (logand (+ +sdefl-sym-max+ 3) (lognot 3)) :initial-element 0))
         (used-sym 0))
    (dotimes (sym sym-cnt)
      (incf (aref cnts (min (aref freqs sym) (1- cnt-num)))))
    (loop for i from 1 below cnt-num
          do (let ((cnt (aref cnts i)))
               (setf (aref cnts i) used-sym)
               (incf used-sym cnt)))
    (dotimes (sym sym-cnt)
      (let ((freq (aref freqs sym)))
        (if (/= freq 0)
            (let ((idx (min freq (1- cnt-num))))
              (setf (aref sym-out (aref cnts idx)) (logand (logior sym (ash freq +sdefl-sym-bits+)) #xffffffff))
              (incf (aref cnts idx)))
            (setf (aref lens sym) 0))))
    (%sdefl-heap-sort sym-out (aref cnts (- cnt-num 2)) (- (aref cnts (- cnt-num 1)) (aref cnts (- cnt-num 2))))
    used-sym))

(defun %sdefl-build-tree (a sym-cnt)
  (let ((i 0) (b 0) (e 0))
    (loop
      (let (m n)
        (if (and (/= i sym-cnt) (or (= b e) (<= (ash (aref a i) -10) (ash (aref a b) -10))))
            (setf m i i (1+ i))
            (setf m b b (1+ b)))
        (if (and (/= i sym-cnt) (or (= b e) (<= (ash (aref a i) -10) (ash (aref a b) -10))))
            (setf n i i (1+ i))
            (setf n b b (1+ b)))
        (let ((freq-shift (logand (+ (logand (aref a m) (lognot +sdefl-sym-msk+))
                                     (logand (aref a n) (lognot +sdefl-sym-msk+)))
                                  #xffffffff)))
          (setf (aref a m) (logand (logior (logand (aref a m) +sdefl-sym-msk+) (ash e +sdefl-sym-bits+)) #xffffffff)
                (aref a n) (logand (logior (logand (aref a n) +sdefl-sym-msk+) (ash e +sdefl-sym-bits+)) #xffffffff)
                (aref a e) (logand (logior (logand (aref a e) +sdefl-sym-msk+) freq-shift) #xffffffff))))
      (incf e)
      (unless (> (- sym-cnt e) 1) (return)))))

(defun %sdefl-gen-len-cnt (a root len-cnt max-code-len)
  (loop for i from 0 to max-code-len do (setf (aref len-cnt i) 0))
  (setf (aref len-cnt 1) 2)
  (setf (aref a root) (logand (aref a root) +sdefl-sym-msk+))
  (loop for n downfrom (1- root) to 0
        do (let* ((p (ash (aref a n) -10))
                  (pdepth (ash (aref a p) -10))
                  (depth (1+ pdepth))
                  (len depth))
             (setf (aref a n) (logand (logior (logand (aref a n) +sdefl-sym-msk+) (ash depth +sdefl-sym-bits+)) #xffffffff))
             (when (>= len max-code-len)
               (setf len max-code-len)
               (loop do (decf len) while (zerop (aref len-cnt len))))
             (decf (aref len-cnt len))
             (incf (aref len-cnt (1+ len)) 2))))

(defun %sdefl-gen-codes (a lens len-cnt max-code-word-len sym-cnt)
  (let ((i 0) (nxt (make-array 16 :initial-element 0)))
    (loop for len downfrom max-code-word-len to 1
          do (dotimes (k (aref len-cnt len))
               (setf (aref lens (logand (aref a i) +sdefl-sym-msk+)) len)
               (incf i)))
    (loop for len from 2 to max-code-word-len
          do (setf (aref nxt len) (logand (ash (+ (aref nxt (1- len)) (aref len-cnt (1- len))) 1) #xffffffff)))
    (dotimes (sym sym-cnt)
      (setf (aref a sym) (aref nxt (aref lens sym)))
      (incf (aref nxt (aref lens sym))))))

(defun %sdefl-rev (c n)
  (setf c (logior (ash (logand c #x5555) 1) (ash (logand c #xAAAA) -1)))
  (setf c (logior (ash (logand c #x3333) 2) (ash (logand c #xCCCC) -2)))
  (setf c (logior (ash (logand c #x0F0F) 4) (ash (logand c #xF0F0) -4)))
  (setf c (logior (ash (logand c #x00FF) 8) (ash (logand c #xFF00) -8)))
  (ash c (- (- 16 n))))

(defun %sdefl-huff (lens codes freqs num-syms max-code-len)
  (let* ((a codes)
         (len-cnt (make-array 16 :initial-element 0))
         (used-syms (%sdefl-sort-sym num-syms freqs lens a)))
    (cond ((zerop used-syms))
          ((= used-syms 1)
           (let* ((s (logand (aref a 0) +sdefl-sym-msk+))
                  (i (if (/= s 0) s 1)))
             (setf (aref codes 0) 0 (aref lens 0) 1
                   (aref codes i) 1 (aref lens i) 1)))
          (t
           (%sdefl-build-tree a used-syms)
           (%sdefl-gen-len-cnt a (- used-syms 2) len-cnt max-code-len)
           (%sdefl-gen-codes a lens len-cnt max-code-len num-syms)
           (dotimes (c num-syms)
             (setf (aref codes c) (%sdefl-rev (aref codes c) (aref lens c))))))))

(defun %sdefl-precode (freqs items litlen offlen)
  "Returns (values item-count lit off)"
  (let ((lit +sdefl-sym-max+) (off +sdefl-off-max+) (at 0) (run-start 0))
    (loop while (> lit 257) do (if (/= (aref litlen (1- lit)) 0) (return) (decf lit)))
    (loop while (> off 1) do (if (/= (aref offlen (1- off)) 0) (return) (decf off)))
    (let* ((total (+ lit off))
           (lens (make-array total)))
      (replace lens litlen :end2 lit)
      (replace lens offlen :start1 lit :end2 off)
      (flet ((emit (item) (setf (aref items at) item) (incf at)))
        (loop
          (let* ((len (aref lens run-start))
                 (run-end run-start))
            (loop do (incf run-end) while (and (/= run-end total) (= len (aref lens run-end))))
            (cond ((zerop len)
                   (loop while (>= (- run-end run-start) 11)
                         do (let* ((n (- run-end run-start 11))
                                   (xbits (min n #x7f)))
                              (incf (aref freqs 18))
                              (emit (logior 18 (ash xbits 5)))
                              (incf run-start (+ 11 xbits))))
                   (when (>= (- run-end run-start) 3)
                     (let* ((n (- run-end run-start 3))
                            (xbits (min n 7)))
                       (incf (aref freqs 17))
                       (emit (logior 17 (ash xbits 5)))
                       (incf run-start (+ 3 xbits)))))
                  ((>= (- run-end run-start) 4)
                   (incf (aref freqs len))
                   (emit len)
                   (incf run-start)
                   (loop do (let ((xbits (min (- run-end run-start 3) 3)))
                              (emit (logior 16 (ash xbits 5)))
                              (incf run-start (+ 3 xbits))
                              (incf (aref freqs 16)))
                         while (>= (- run-end run-start) 3))))
            (loop while (/= run-start run-end)
                  do (incf (aref freqs len))
                     (emit len)
                     (incf run-start)))
          (when (= run-start total) (return))))
      (values at lit off))))

(alexandria:define-constant +sdefl-lslot+
  (coerce '(0 0 0 0 1 2 3 4 5 6 7 8 8 9 9 10 10 11 11 12 12 12
            12 13 13 13 13 14 14 14 14 15 15 15 15 16 16 16 16 16
            16 16 16 17 17 17 17 17 17 17 17 18 18 18 18 18 18 18
            18 19 19 19 19 19 19 19 19 20 20 20 20 20 20 20 20 20
            20 20 20 20 20 20 20 21 21 21 21 21 21 21 21 21 21 21
            21 21 21 21 21 22 22 22 22 22 22 22 22 22 22 22 22 22
            22 22 22 23 23 23 23 23 23 23 23 23 23 23 23 23 23 23
            23 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 24
            24 24 24 24 24 24 24 24 24 24 24 24 24 24 24 25 25 25
            25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25 25
            25 25 25 25 25 25 25 25 25 25 25 26 26 26 26 26 26 26
            26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26 26
            26 26 26 26 26 26 26 27 27 27 27 27 27 27 27 27 27 27
            27 27 27 27 27 27 27 27 27 27 27 27 27 27 27 27 27 27
            27 27 28)
          'simple-vector)
  :test #'equalp)

(alexandria:define-constant +sdefl-dxmax+ #(0 6 12 24 48 96 192 384 768 1536 3072 6144 12288 24576) :test #'equalp)

(defun %sdefl-match-codes (dist len)
  "Returns (values ls lc dc dx)"
  (let* ((ls (svref +sdefl-lslot+ len))
         (lc (+ 257 ls))
         (dx (%sdefl-ilog2 (ash (%sdefl-npow2 dist) -2)))
         (dc (if (/= dx 0) (+ (ash (1+ dx) 1) (if (> dist (svref +sdefl-dxmax+ dx)) 1 0)) (1- dist))))
    (values ls lc dc dx)))

(alexandria:define-constant +sdefl-x-pre-bits+ #(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 3 7) :test #'equalp)
(alexandria:define-constant +sdefl-x-len-bits+ #(0 0 0 0 0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 0) :test #'equalp)
(alexandria:define-constant +sdefl-x-off-bits+ #(0 0 0 0 1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9 10 10 11 11 12 12 13 13) :test #'equalp)

(defun %sdefl-blk-dyn-p (s blk-len pre-item-len pre-freq pre-len)
  "sdefl_blk_type() == SDEFL_BLK_DYN"
  (let ((dyn-cost (+ 5 5 4 (* 3 pre-item-len)))
        (fix-cost 0))
    (dotimes (sym +sdefl-pre-max+)
      (incf dyn-cost (* (aref pre-freq sym) (+ (svref +sdefl-x-pre-bits+ sym) (aref pre-len sym)))))
    (dotimes (sym 256)
      (incf dyn-cost (* (aref (sdefl-freq-lit s) sym) (aref (sdefl-len-lit s) sym))))
    (incf dyn-cost (aref (sdefl-len-lit s) +sdefl-eob+))
    (loop for sym from 257 below 286
          do (incf dyn-cost (* (aref (sdefl-freq-lit s) sym) (+ (svref +sdefl-x-len-bits+ (- sym 257)) (aref (sdefl-len-lit s) sym)))))
    (dotimes (sym 30)
      (incf dyn-cost (* (aref (sdefl-freq-off s) sym) (+ (svref +sdefl-x-off-bits+ sym) (aref (sdefl-len-off s) sym)))))
    (setf dyn-cost (%i32 (logand dyn-cost #xffffffff)))
    (incf fix-cost (* 8 (+ (* 5 (%sdefl-div-round-up blk-len +sdefl-raw-blk-size+)) blk-len 1 2)))
    (< dyn-cost fix-cost)))

(alexandria:define-constant +sdefl-lxn+ #(0 0 0 0 0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 0) :test #'equalp)
(alexandria:define-constant +sdefl-lmin+ #(3 4 5 6 7 8 9 10 11 13 15 17 19 23 27 31 35 43 51 59 67 83 99 115 131 163 195 227 258)
  :test #'equalp)
(alexandria:define-constant +sdefl-dmin+ #(1 2 3 4 5 7 9 13 17 25 33 49 65 97 129 193 257 385 513 769 1025 1537 2049 3073 4097
                                          6145 8193 12289 16385 24577)
  :test #'equalp)

(defun %sdefl-match (s dist len)
  (multiple-value-bind (ls lc dc dx) (%sdefl-match-codes dist len)
    (%sdefl-put s (aref (sdefl-word-lit s) lc) (aref (sdefl-len-lit s) lc))
    (%sdefl-put s (- len (svref +sdefl-lmin+ ls)) (svref +sdefl-lxn+ ls))
    (%sdefl-put s (aref (sdefl-word-off s) dc) (aref (sdefl-len-off s) dc))
    (%sdefl-put s (- dist (svref +sdefl-dmin+ dc)) dx)))

(alexandria:define-constant +sdefl-perm+ #(16 17 18 0 8 7 9 6 10 5 11 4 12 3 13 2 14 1 15) :test #'equalp)

(defun %sdefl-flush (s is-last in blk-begin blk-end)
  (let ((blk-len (- blk-end blk-begin))
        (codes (make-array +sdefl-pre-max+ :element-type '(unsigned-byte 32) :initial-element 0))
        (lens (make-array +sdefl-pre-max+ :element-type '(unsigned-byte 8) :initial-element 0))
        (freqs (make-array +sdefl-pre-max+ :element-type '(unsigned-byte 32) :initial-element 0))
        (items (make-array (+ +sdefl-sym-max+ +sdefl-off-max+) :initial-element 0))
        (item-cnt 0))
    ;; calculate huffman codes
    (incf (aref (sdefl-freq-lit s) +sdefl-eob+))
    (%sdefl-huff (sdefl-len-lit s) (sdefl-word-lit s) (sdefl-freq-lit s) +sdefl-sym-max+ +sdefl-lit-len-codes+)
    (%sdefl-huff (sdefl-len-off s) (sdefl-word-off s) (sdefl-freq-off s) +sdefl-off-max+ +sdefl-off-codes+)
    (multiple-value-bind (symcnt-items symcnt-lit symcnt-off) (%sdefl-precode freqs items (sdefl-len-lit s) (sdefl-len-off s))
      (%sdefl-huff lens codes freqs +sdefl-pre-max+ +sdefl-pre-codes+)
      (setf item-cnt +sdefl-pre-max+)
      (loop while (> item-cnt 4)
            do (if (/= (aref lens (svref +sdefl-perm+ (1- item-cnt))) 0) (return) (decf item-cnt)))
      ;; write block
      (if (not (%sdefl-blk-dyn-p s blk-len item-cnt freqs lens))
          ;; uncompressed blocks
          (let ((n (%sdefl-div-round-up blk-len +sdefl-raw-blk-size+)))
            (dotimes (i n)
              (let ((fin (and is-last (= (1+ i) n)))
                    (amount (min blk-len +sdefl-raw-blk-size+)))
                (%sdefl-put s (if fin 1 0) 1)          ; block
                (%sdefl-put s 0 2)                     ; stored block
                (when (/= (sdefl-bitcnt s) 0)
                  (%sdefl-put s 0 (- 8 (sdefl-bitcnt s))))
                (%sdefl-put s (logand amount #xff) 8)
                (%sdefl-put s (ash (logand amount #xffff) -8) 8)
                (let ((namount (logand (lognot amount) #xffff)))
                  (%sdefl-put s (logand namount #xff) 8)
                  (%sdefl-put s (ash namount -8) 8))
                (loop for k from (+ blk-begin (* i +sdefl-raw-blk-size+)) repeat amount
                      do (vector-push-extend (aref in k) (sdefl-out s)))
                (decf blk-len amount))))
          ;; dynamic huffman block
          (progn
            (%sdefl-put s (if is-last 1 0) 1)          ; block
            (%sdefl-put s 2 2)                         ; dynamic huffman
            (%sdefl-put s (- symcnt-lit 257) 5)
            (%sdefl-put s (- symcnt-off 1) 5)
            (%sdefl-put s (- item-cnt 4) 4)
            (dotimes (i item-cnt)
              (%sdefl-put s (aref lens (svref +sdefl-perm+ i)) 3))
            (dotimes (i symcnt-items)
              (let ((sym (logand (aref items i) #x1f)))
                (%sdefl-put s (aref codes sym) (aref lens sym))
                (case sym
                  (16 (%sdefl-put s (ash (aref items i) -5) 2))
                  (17 (%sdefl-put s (ash (aref items i) -5) 3))
                  (18 (%sdefl-put s (ash (aref items i) -5) 7)))))
            ;; block sequences
            (loop for (off . len) across (sdefl-seq s)
                  do (if (>= off 0)
                         (dotimes (j len)
                           (let ((c (aref in (+ off j))))
                             (%sdefl-put s (aref (sdefl-word-lit s) c) (aref (sdefl-len-lit s) c))))
                         (%sdefl-match s (- off) len)))
            (%sdefl-put s (aref (sdefl-word-lit s) +sdefl-eob+) (aref (sdefl-len-lit s) +sdefl-eob+)))))
    (fill (sdefl-freq-lit s) 0)
    (fill (sdefl-freq-off s) 0)
    (setf (fill-pointer (sdefl-seq s)) 0)))

(defun %sdefl-reg-match (s off len)
  (multiple-value-bind (ls lc dc) (%sdefl-match-codes off len)
    (declare (ignore ls))
    (incf (aref (sdefl-freq-lit s) lc))
    (incf (aref (sdefl-freq-off s) dc))))

(defun %sdefl-fnd (s chain-len max-match in p m-off m-len)
  "Returns the match (values off len) starting from (M-OFF M-LEN)"
  (declare (type (simple-array (unsigned-byte 8) (*)) in) (type fixnum p chain-len max-match m-off m-len))
  (let* ((tbl (sdefl-tbl s)) (prv (sdefl-prv s))
         (i (aref tbl (%sdefl-hash32 in p)))
         (limit (if (< (- p +sdefl-win-siz+) +sdefl-nil+) +sdefl-nil+ (- p +sdefl-win-siz+)))
         (len (length in)))
    (declare (type fixnum i limit len))
    (flet ((b (k) (if (< -1 k len) (aref in k) 0)))
      (declare (inline b))
      (loop while (> i limit)
            do (when (and (= (b (+ i m-len)) (b (+ p m-len)))
                          (= (%sdefl-uload32 in i) (%sdefl-uload32 in p)))
                 (let ((n +sdefl-min-match+))
                   (declare (type fixnum n))
                   (loop while (and (< n max-match) (= (b (+ i n)) (b (+ p n)))) do (incf n))
                   (when (> n m-len)
                     (setf m-len n m-off (- p i))
                     (when (= n max-match) (return)))))
               (when (zerop (decf chain-len)) (return))
               (setf i (aref prv (logand i +sdefl-win-msk+)))))
    (values m-off m-len)))

(defun %sdefl-compr (s in in-len lvl)
  (declare (type (simple-array (unsigned-byte 8) (*)) in) (type fixnum in-len lvl))
  (let ((pref #(8 10 14 24 30 48 65 96 130))
        (max-chain (if (< lvl 8) (ash 1 (1+ lvl)) (ash 1 13)))
        (i 0) (litlen 0)
        (tbl (sdefl-tbl s)) (prv (sdefl-prv s)))
    (declare (type fixnum i litlen max-chain))
    (fill tbl +sdefl-nil+)
    (flet ((seq (off len) (vector-push-extend (cons off len) (sdefl-seq s))))
      (loop
        (let ((blk-begin i)
              (blk-end (if (< (+ i +sdefl-blk-max+) in-len) (+ i +sdefl-blk-max+) in-len)))
          (loop while (< i blk-end)
                do (let* ((m-off 0) (m-len 0)
                          (left (- blk-end i))
                          (max-match (if (> left +sdefl-max-match+) +sdefl-max-match+ left))
                          (nice-match (min (svref pref lvl) max-match))
                          (run 1) (inc 1) (run-inc 0))
                     (declare (type fixnum m-off m-len run inc run-inc))
                     (when (> max-match +sdefl-min-match+)
                       (multiple-value-setq (m-off m-len) (%sdefl-fnd s max-chain max-match in i 0 0)))
                     (when (and (>= lvl 5) (>= m-len +sdefl-min-match+) (< (1+ m-len) nice-match))
                       (multiple-value-bind (m2-off m2-len) (%sdefl-fnd s max-chain (1+ m-len) in (1+ i) 0 0)
                         (declare (ignore m2-off))
                         (setf m-len (if (> m2-len m-len) 0 m-len))))
                     (if (>= m-len +sdefl-min-match+)
                         (progn
                           (when (/= litlen 0)
                             (seq (- i litlen) litlen)
                             (setf litlen 0))
                           (seq (- m-off) m-len)
                           (%sdefl-reg-match s m-off m-len)
                           (if (and (< lvl 2) (>= m-len nice-match))
                               (setf inc m-len)
                               (setf run m-len)))
                         (progn
                           (incf (aref (sdefl-freq-lit s) (aref in i)))
                           (incf litlen)))
                     (setf run-inc (* run inc))
                     (if (> (- in-len (+ i run-inc)) +sdefl-min-match+)
                         (loop while (> run 0)
                               do (decf run)
                                  (let ((h (%sdefl-hash32 in i)))
                                    (setf (aref prv (logand i +sdefl-win-msk+)) (aref tbl h)
                                          (aref tbl h) i)
                                    (incf i inc)))
                         (incf i run-inc))))
          (when (/= litlen 0)
            (seq (- i litlen) litlen)
            (setf litlen 0))
          (%sdefl-flush s (= blk-end in-len) in blk-begin blk-end))
        (unless (< i in-len) (return))))
    (when (/= (sdefl-bitcnt s) 0)
      (%sdefl-put s 0 (- 8 (sdefl-bitcnt s))))))

(defun sdeflate (in n lvl)
  "Compress N bytes of IN into a raw DEFLATE stream, returns the compressed octets"
  (let ((s (%make-sdefl :out (make-array (sdefl-bound n) :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0)))
        (in (coerce in '(simple-array (unsigned-byte 8) (*)))))
    (setf (sdefl-bits s) 0 (sdefl-bitcnt s) 0)
    (%sdefl-compr s in n lvl)
    (coerce (sdefl-out s) '(simple-array (unsigned-byte 8) (*)))))

(defun sdefl-bound (len)
  (let ((max-blocks (+ 1 (%sdefl-div-round-up len +sdefl-raw-blk-size+))))
    (+ (* 5 max-blocks) len 1 4 8)))
